version: "3.9"

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Web UI
    environment:
      MINIO_ROOT_USER: uz-kosmos
      MINIO_ROOT_PASSWORD: bmvFEj9WB39GKhqzuKmb
    volumes:
      - ./minio-data:/data
    command: server /data --console-address ":9001"
